version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: etl_imo_postgres
    environment:
      POSTGRES_DB: batch_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d batch_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - etl_network

volumes:
  postgres_data:
    driver: local

networks:
  etl_network:
    driver: bridge
